name: Build Telegram Bot API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make git zlib1g-dev libssl-dev gperf cmake \
          clang-14 libc++-14-dev libc++abi-14-dev
        
    - name: Configure and build
      run: |
        mkdir build
        cd build
        CXXFLAGS="-stdlib=libc++" CC=clang-14 CXX=clang++-14 \
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../install ..
        cmake --build . --target install
        
    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot-api
        path: install/bin/telegram-bot-api
